name: Build and push multi-arch image on separate runners

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA to build the image from'
        required: false
      image_tag:
        description: 'Desired Docker image tag'
        required: false
        default: 'latest'

jobs:
  build-amd64:
    name: Build amd64
    runs-on: ubuntu-latest

    steps:
      - name: Determine commit/tag
        id: set-vars
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ -n "${{ github.event.inputs.commit_sha }}" ]; then
              echo "COMMIT_SHA=${{ github.event.inputs.commit_sha }}" >> $GITHUB_ENV
            else
              echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
            fi
          else
            echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
          fi

          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ -n "${{ github.event.inputs.image_tag }}" ]; then
              echo "IMAGE_TAG=${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV
            else
              echo "IMAGE_TAG=latest" >> $GITHUB_ENV
            fi
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          fi

          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMIT_SHA }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build amd64 image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}-amd64
            ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }}-amd64
          build-args: |
            ARCH=amd64

  build-arm64:
    name: Build arm64
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Determine commit/tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ -n "${{ github.event.inputs.commit_sha }}" ]; then
              echo "COMMIT_SHA=${{ github.event.inputs.commit_sha }}" >> $GITHUB_ENV
            else
              echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
            fi
          else
            echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
          fi

          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ -n "${{ github.event.inputs.image_tag }}" ]; then
              echo "IMAGE_TAG=${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV
            else
              echo "IMAGE_TAG=latest" >> $GITHUB_ENV
            fi
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          fi

          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMIT_SHA }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build arm64 image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}-arm64
            ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }}-arm64
          build-args: |
            ARCH=arm64

  create-manifest:
    name: Create Multi-Arch Manifests
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge into single multi-arch for "latest" (or the chosen IMAGE_TAG)
        run: |
          docker manifest create ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }} \
            --amend ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}-amd64 \
            --amend ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}-arm64

          docker manifest push ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}

      - name: Merge into single multi-arch for the short commit SHA
        run: |
          docker manifest create ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }} \
            --amend ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }}-amd64 \
            --amend ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }}-arm64

          docker manifest push ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }}
